/**
 * POST /api/db/seed
 * One-time endpoint: seeds Supabase with all providers from SEED_PROVIDERS
 * and creates the admin user.
 *
 * Requires header: x-seed-secret: <BYT_SEED_SECRET env var>
 *
 * DISABLE or DELETE this file after running once.
 */
const supabase = require('./_supabase');
const bcrypt   = require('bcryptjs');

// Inline the seed data here so Vercel has it at runtime.
// This is generated by scripts/export_seed.js
const SEED = require('../../scripts/_seed_data.json');

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  const secret = req.headers['x-seed-secret'];
  if (!secret || secret !== process.env.BYT_SEED_SECRET) {
    return res.status(403).json({ error: 'Forbidden' });
  }

  const results = { providers: 0, users: 0, errors: [] };

  // 1. Upsert all providers
  for (const p of SEED.providers) {
    const row = {
      id:               p.id,
      company_name:     p.companyName,
      trade_type:       p.tradeType,
      description:      p.description || '',
      contact_name:     p.contactName || '',
      email:            p.email || '',
      phone:            p.phone || '',
      website:          p.website || '',
      license_number:   p.licenseNumber || '',
      years_in_business: p.yearsInBusiness || '',
      service_areas:    p.serviceAreas || [],
      city:             p.city || '',
      province:         p.province || 'ON',
      rating:           p.rating || 0,
      review_count:     p.reviewCount || 0,
      certifications:   p.certifications || [],
      featured:         p.featured || false,
      claimed:          p.claimed || false,
      request_count:    p.requestCount || 0,
      status:           p.status === 'pending' || p.status === 'pending_approval' ? p.status : 'active',
      plan:             p.plan || 'free',
      source:           p.source || 'seed',
      profile_type:     p.profileType || 'company',
    };
    const { error } = await supabase.from('providers').upsert(row, { onConflict: 'id' });
    if (error) results.errors.push({ id: p.id, error: error.message });
    else results.providers++;
  }

  // 2. Create admin user
  const adminHash = await bcrypt.hash('BYT@dmin2026!', 10);
  const { error: adminErr } = await supabase.from('users').upsert({
    id: 'admin-01', email: 'admin@bookyourtrades.com',
    password_hash: adminHash, role: 'admin', verified: true, name: 'Admin'
  }, { onConflict: 'email' });
  if (adminErr) results.errors.push({ id: 'admin', error: adminErr.message });
  else results.users++;

  // 3. Create provider user accounts (email + temp password from seed)
  for (const p of SEED.providers) {
    if (!p.email || !p.password) continue;
    const hash = await bcrypt.hash(p.password, 10);
    const { error } = await supabase.from('users').upsert({
      id: 'u' + p.id, email: p.email,
      password_hash: hash, role: 'provider',
      provider_id: p.id, name: p.contactName || p.companyName,
      verified: p.status === 'active',
    }, { onConflict: 'email' });
    if (!error) results.users++;
  }

  res.status(200).json({ message: 'Seed complete', ...results });
};
