import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
content = open('C:/Personal/trades-ontario/index.html', 'r', encoding='utf-8', newline='').read()

SEED_RFQS_JS = (
"// -- Seed RFQ / Lead Data -- 25 demo leads covering all trade types\r\n"
"const SEED_RFQS = [\r\n"
"  { id:'rfq1',  tradeType:'Electrical',           title:'Commercial Panel Upgrade',            city:'Toronto',    province:'ON', budget:'$3,000-$6,000',    timeline:'Within 2 weeks',   urgency:'high',   contactName:'Marcus Webb',      contactEmail:'m.webb@retailgroup.ca',      contactPhone:'416-555-0182', jobDescription:'200A panel upgrade for 3,200 sq ft retail unit in Etobicoke. ESA permit filing required.', status:'open', createdAt:'2026-04-29T14:22:00Z' },\r\n"
"  { id:'rfq2',  tradeType:'Plumbing',              title:'Washroom Rough-in -- Office Build',    city:'Mississauga',province:'ON', budget:'$8,000-$14,000',   timeline:'3-4 weeks',        urgency:'normal', contactName:'Sandra Osei',      contactEmail:'s.osei@buildgroup.ca',       contactPhone:'905-555-0241', jobDescription:'New washroom rough-in for 4-fixture commercial washroom in 6-story office building.', status:'open', createdAt:'2026-04-28T09:15:00Z' },\r\n"
"  { id:'rfq3',  tradeType:'HVAC',                  title:'RTU Replacement -- Warehouse',         city:'Brampton',   province:'ON', budget:'$18,000-$28,000',  timeline:'ASAP',             urgency:'high',   contactName:'Dave Kurzman',     contactEmail:'d.kurzman@logisticsinc.ca',   contactPhone:'905-555-0394', jobDescription:'Replace aging 20-ton rooftop unit at 40,000 sq ft distribution centre. TSSA certification required.', status:'open', createdAt:'2026-04-29T08:00:00Z' },\r\n"
"  { id:'rfq4',  tradeType:'Roofing',               title:'Flat Roof Membrane Replacement',       city:'Hamilton',   province:'ON', budget:'$22,000-$35,000',  timeline:'2-3 weeks',        urgency:'normal', contactName:'Lisa Tran',        contactEmail:'l.tran@hamiltonprop.ca',     contactPhone:'905-555-0117', jobDescription:'TPO membrane replacement on 8,000 sq ft flat commercial roof. Quotes needed ASAP.', status:'open', createdAt:'2026-04-27T16:45:00Z' },\r\n"
"  { id:'rfq5',  tradeType:'General Contracting',   title:'Office Tenant Improvement 4,000 sqft', city:'Ottawa',     province:'ON', budget:'$60,000-$90,000',  timeline:'6-8 weeks',        urgency:'normal', contactName:'Priya Singh',      contactEmail:'p.singh@govtech.ca',         contactPhone:'613-555-0278', jobDescription:'Full interior TI for new tech company tenant -- demising walls, new flooring, lighting, washrooms.', status:'open', createdAt:'2026-04-26T11:30:00Z' },\r\n"
"  { id:'rfq6',  tradeType:'Electrical',            title:'LED Retrofit -- Office Tower',         city:'Vancouver',  province:'BC', budget:'$12,000-$20,000',  timeline:'3-4 weeks',        urgency:'normal', contactName:'Ryan Cho',         contactEmail:'r.cho@propertywest.ca',      contactPhone:'604-555-0351', jobDescription:'LED retrofit of all common areas on 14-floor office tower. ~600 fixtures. BC Hydro incentive required.', status:'open', createdAt:'2026-04-28T13:00:00Z' },\r\n"
"  { id:'rfq7',  tradeType:'Plumbing',              title:'Grease Trap Install -- Restaurant',    city:'Calgary',    province:'AB', budget:'$6,000-$10,000',   timeline:'2 weeks',          urgency:'high',   contactName:'Maria Delgado',    contactEmail:'m.delgado@foodgroup.ca',     contactPhone:'403-555-0194', jobDescription:'Supply and install 100 GPM grease trap for new 80-seat restaurant. City of Calgary FOG bylaw compliance.', status:'open', createdAt:'2026-04-29T10:10:00Z' },\r\n"
"  { id:'rfq8',  tradeType:'HVAC',                  title:'Chiller Plant Service Contract',       city:'Toronto',    province:'ON', budget:'Contract TBD',     timeline:'Ongoing',          urgency:'normal', contactName:'Peter Okonkwo',    contactEmail:'p.okonkwo@facilitymgmt.ca',  contactPhone:'416-555-0462', jobDescription:'Certified chiller technician for preventive maintenance on 200-ton York centrifugal chiller. Annual contract.', status:'open', createdAt:'2026-04-25T09:00:00Z' },\r\n"
"  { id:'rfq9',  tradeType:'Welding & Fabrication', title:'Structural Steel Mezzanine Addition',  city:'Edmonton',   province:'AB', budget:'$25,000-$40,000',  timeline:'4-5 weeks',        urgency:'normal', contactName:'Rob Ference',      contactEmail:'r.ference@industrialco.ca',  contactPhone:'780-555-0283', jobDescription:'Design-build mezzanine addition inside existing warehouse. ~3,000 sq ft at 12ft elevation. CWB certification.', status:'open', createdAt:'2026-04-27T14:20:00Z' },\r\n"
"  { id:'rfq10', tradeType:'Concrete & Masonry',    title:'Parking Deck Repair -- Commercial',    city:'Mississauga',province:'ON', budget:'$40,000-$70,000',  timeline:'3-6 weeks',        urgency:'high',   contactName:'Asha Nair',        contactEmail:'a.nair@plazamgmt.ca',        contactPhone:'905-555-0536', jobDescription:'Structural repair of 300-space parking deck. Spall repair, waterproofing, traffic coating. PE stamp required.', status:'open', createdAt:'2026-04-28T15:30:00Z' },\r\n"
"  { id:'rfq11', tradeType:'Carpentry',             title:'Wood Feature Wall -- Corporate Lobby', city:'Toronto',    province:'ON', budget:'$15,000-$25,000',  timeline:'3 weeks',          urgency:'normal', contactName:'Jennifer Lau',     contactEmail:'j.lau@archfirm.ca',          contactPhone:'416-555-0619', jobDescription:'Custom white oak slatted feature wall in 30-ft lobby. Designer drawings available. Fine finish carpenter.', status:'open', createdAt:'2026-04-26T09:00:00Z' },\r\n"
"  { id:'rfq12', tradeType:'Sheet Metal',           title:'Kitchen Exhaust Hood & Ductwork',      city:'Winnipeg',   province:'MB', budget:'$8,000-$14,000',   timeline:'3 weeks',          urgency:'normal', contactName:'Kevin Brant',      contactEmail:'k.brant@restaurantdev.ca',   contactPhone:'204-555-0247', jobDescription:'Custom Type I hood system and stainless ductwork for commercial kitchen expansion. SMACNA standards.', status:'open', createdAt:'2026-04-29T11:45:00Z' },\r\n"
"  { id:'rfq13', tradeType:'Fire Protection',       title:'Sprinkler System -- New Warehouse',    city:'Calgary',    province:'AB', budget:'$35,000-$55,000',  timeline:'6-8 weeks',        urgency:'normal', contactName:'Tom Greer',        contactEmail:'t.greer@westlogistics.ca',   contactPhone:'403-555-0381', jobDescription:'Design-install wet pipe sprinkler system for 60,000 sq ft warehouse. NFPA 13 required.', status:'open', createdAt:'2026-04-24T14:00:00Z' },\r\n"
"  { id:'rfq14', tradeType:'Painting & Coating',    title:'Industrial Floor Coating -- Food Plant',city:'Hamilton',  province:'ON', budget:'$18,000-$28,000',  timeline:'Weekends only',    urgency:'normal', contactName:'Julie Mosher',     contactEmail:'j.mosher@foodmfg.ca',        contactPhone:'905-555-0174', jobDescription:'Epoxy floor coating for 12,000 sq ft food manufacturing facility. USDA-approved coating. Weekend shifts.', status:'open', createdAt:'2026-04-27T10:20:00Z' },\r\n"
"  { id:'rfq15', tradeType:'Demolition',            title:'Interior Demo -- 3-Floor Office',      city:'Toronto',    province:'ON', budget:'$20,000-$35,000',  timeline:'2-3 weeks',        urgency:'high',   contactName:'Ahmed Khalil',     contactEmail:'a.khalil@redevelopco.ca',    contactPhone:'416-555-0745', jobDescription:'Selective interior demo on floors 8-10 of Yonge St office tower. Non-load-bearing walls, ceilings, millwork.', status:'open', createdAt:'2026-04-29T09:30:00Z' },\r\n"
"  { id:'rfq16', tradeType:'Insulation',            title:'Spray Foam -- Cold Storage Build',     city:'Vancouver',  province:'BC', budget:'$12,000-$20,000',  timeline:'3-4 weeks',        urgency:'normal', contactName:'Grace Kim',        contactEmail:'g.kim@coldchain.ca',         contactPhone:'604-555-0428', jobDescription:'Closed-cell spray foam for new 5,000 sq ft cold storage room. R-40 minimum. Vapour barrier included.', status:'open', createdAt:'2026-04-26T14:00:00Z' },\r\n"
"  { id:'rfq17', tradeType:'Flooring',              title:'LVT Installation -- Medical Office',   city:'Ottawa',     province:'ON', budget:'$9,000-$15,000',   timeline:'2 weeks',          urgency:'normal', contactName:'Dr. Natasha Bowen',contactEmail:'n.bowen@medclinic.ca',      contactPhone:'613-555-0551', jobDescription:'5,000 sq ft LVT flooring replacement in active medical clinic. Must work after hours. Rubber base throughout.', status:'open', createdAt:'2026-04-28T10:30:00Z' },\r\n"
"  { id:'rfq18', tradeType:'Security Systems',      title:'Access Control -- Multi-Tenant Office',city:'Edmonton',   province:'AB', budget:'$18,000-$30,000',  timeline:'4-5 weeks',        urgency:'normal', contactName:'Frank Li',         contactEmail:'f.li@eastwestprop.ca',       contactPhone:'780-555-0392', jobDescription:'IP-based access control for 8-story office building. 24 doors, elevator integration, cloud management.', status:'open', createdAt:'2026-04-25T11:00:00Z' },\r\n"
"  { id:'rfq19', tradeType:'Millwright',            title:'Conveyor System Rebuild -- Food Plant', city:'Mississauga',province:'ON', budget:'$30,000-$50,000',  timeline:'Planned shutdown',  urgency:'normal', contactName:'Steve Bouchard',  contactEmail:'s.bouchard@foodline.ca',     contactPhone:'905-555-0618', jobDescription:'Rebuild and realignment of 400ft conveyor system during planned 2-week plant shutdown. Red Seal required.', status:'open', createdAt:'2026-04-23T09:00:00Z' },\r\n"
"  { id:'rfq20', tradeType:'Landscaping',           title:'Commercial Grounds Maintenance Contract',city:'Calgary',  province:'AB', budget:'$2,500/mo',         timeline:'Ongoing seasonal',  urgency:'normal', contactName:'Renata Patel',    contactEmail:'r.patel@retailreit.ca',      contactPhone:'403-555-0277', jobDescription:'Year-round grounds maintenance for 6 retail properties across NE Calgary. Snow removal included.', status:'open', createdAt:'2026-04-28T08:00:00Z' },\r\n"
"  { id:'rfq21', tradeType:'Drywall & Plastering',  title:'Drywall Finishers -- Condo Floors 3-8',city:'Toronto',   province:'ON', budget:'$40,000-$65,000',  timeline:'8-12 weeks',        urgency:'normal', contactName:'Paul Varga',      contactEmail:'p.varga@condo-dev.ca',       contactPhone:'416-555-0834', jobDescription:'Drywall installation and Level 4 finish for floors 3-8 of 25-storey condo tower. Coordination required.', status:'open', createdAt:'2026-04-27T13:00:00Z' },\r\n"
"  { id:'rfq22', tradeType:'Paving & Asphalt',      title:'Parking Lot Resurfacing -- Mall',      city:'Winnipeg',   province:'MB', budget:'$45,000-$75,000',  timeline:'Spring 2026',       urgency:'normal', contactName:'Linda Chow',      contactEmail:'l.chow@mallmgmt.ca',         contactPhone:'204-555-0339', jobDescription:'Full milling and resurfacing of 350-stall surface parking lot. Line painting and speed bumps included.', status:'open', createdAt:'2026-04-22T10:00:00Z' },\r\n"
"  { id:'rfq23', tradeType:'Snow Removal',           title:'Snow Removal Contract 2026/27',        city:'Ottawa',    province:'ON', budget:'Seasonal contract', timeline:'Oct 2026 start',    urgency:'normal', contactName:'Marcus Leblanc',  contactEmail:'m.leblanc@govprop.ca',       contactPhone:'613-555-0412', jobDescription:'Snow removal and ice control for 3 federal government buildings in downtown Ottawa. 24/7 response.', status:'open', createdAt:'2026-04-20T14:00:00Z' },\r\n"
"  { id:'rfq24', tradeType:'Boilermaker',            title:'Pressure Vessel Inspection & Repair',  city:'Hamilton',   province:'ON', budget:'$15,000-$25,000',  timeline:'Planned shutdown',  urgency:'high',   contactName:'George Stamos',   contactEmail:'g.stamos@steelco.ca',        contactPhone:'905-555-0163', jobDescription:'NDE inspection and weld repair of (3) ASME pressure vessels during annual maintenance shutdown.', status:'open', createdAt:'2026-04-29T07:00:00Z' },\r\n"
"  { id:'rfq25', tradeType:'Refrigeration',          title:'Walk-In Cooler System -- Grocery',     city:'Vancouver',  province:'BC', budget:'$28,000-$45,000',  timeline:'6 weeks',           urgency:'normal', contactName:'Amy Wong',        contactEmail:'a.wong@grocerychainbc.ca',   contactPhone:'604-555-0587', jobDescription:'Install refrigeration system for 1,200 sq ft walk-in cooler and 400 sq ft freezer. HFC-free preferred.', status:'open', createdAt:'2026-04-26T11:00:00Z' },\r\n"
"];\r\n"
"\r\n"
)

anchor_old = "/* ============================================================\r\n   STORAGE\r\n============================================================ */\r\nconst SEED_VERSION"
anchor_new = SEED_RFQS_JS + "/* ============================================================\r\n   STORAGE\r\n============================================================ */\r\nconst SEED_VERSION"
print("anchor found:", anchor_old in content)
content = content.replace(anchor_old, anchor_new, 1)
open('C:/Personal/trades-ontario/index.html', 'w', encoding='utf-8', newline='').write(content)
print("Done - SEED_RFQS inserted, length:", len(content))
