import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
content = open('C:/Personal/trades-ontario/index.html', 'r', encoding='utf-8', newline='').read()

# ── 1. Replace the stats grid + tab bar block ─────────────────────────────────
OLD_STATS_TABS = (
"    <div class=\"container\" style=\"padding-top:40px;padding-bottom:80px;\">\r\n"
"      <div class=\"dash-stats\" style=\"display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:40px;\">\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\">${bookings.length}</div><div class=\"stat-label\">Total Bookings</div></div>\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\" style=\"color:#F0A030;\">${pending.length}</div><div class=\"stat-label\">Awaiting Review</div></div>\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\" style=\"color:#22C55E;\">${confirmed.length}</div><div class=\"stat-label\">Confirmed</div></div>\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\">${profileViews}</div><div class=\"stat-label\">Profile Views</div></div>\r\n"
"      </div>\r\n"
"\r\n"
"      <div class=\"tab-bar\">\r\n"
"        <button class=\"tab-btn active\" onclick=\"switchTab('tab-appt',this)\">&#128197; Appointments</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-analytics',this)\">&#128200; Analytics</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-notifs',this)\">\r\n"
"          &#128276; Notifications${unread>0?` <span style=\"background:var(--o500);color:white;border-radius:50%;width:18px;height:18px;display:inline-flex;align-items:center;justify-content:center;font-size:10px;margin-left:4px;\">${unread}</span>`:''}\r\n"
"        </button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-reviews',this)\">&#9733; Reviews</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-profile',this)\">&#9881;&#65039; Profile</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-reputation',this)\">&#127942; Reputation &amp; XP</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-avail',this)\">&#128336; Availability</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-jobs',this)\">&#128203; Available Careers</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-post-job',this)\">&#128226; Post a Job</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-photos',this)\">&#128247; Photos</button>\r\n"
"      </div>"
)

NEW_STATS_TABS = (
"    <div class=\"container\" style=\"padding-top:40px;padding-bottom:80px;\">\r\n"
"\r\n"
"      ${(function(){\r\n"
"        /* ── Onboarding card — only shown when profile is thin ── */\r\n"
"        const profileComplete = !!(prov.phone && prov.certifications && prov.certifications.length && prov.description && prov.description.length > 60 && prov.website);\r\n"
"        if (bookings.length === 0 && !profileComplete) {\r\n"
"          const steps = [\r\n"
"            { done: !!(prov.phone),                            label: 'Add your phone number' },\r\n"
"            { done: !!(prov.website),                          label: 'Add your website URL' },\r\n"
"            { done: !!(prov.description && prov.description.length > 60), label: 'Write a company description (60+ chars)' },\r\n"
"            { done: !!(prov.certifications && prov.certifications.length), label: 'Add certifications / licences' },\r\n"
"            { done: !!(prov.logoUrl),                          label: 'Upload your company logo' },\r\n"
"          ];\r\n"
"          const doneCount = steps.filter(s=>s.done).length;\r\n"
"          const pct = Math.round(doneCount / steps.length * 100);\r\n"
"          return '<div style=\"background:linear-gradient(135deg,#0A1929,#0F2744);border:1px solid rgba(99,179,237,0.25);border-radius:12px;padding:28px 32px;margin-bottom:32px;\">'\r\n"
"            + '<div style=\"display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px;margin-bottom:20px;\">'\r\n"
"            + '<div>'\r\n"
"            + '<div style=\"font-family:\\'Barlow Condensed\\',sans-serif;font-weight:700;font-size:22px;color:white;margin-bottom:4px;\">&#127881; Welcome to BookYourTrades!</div>'\r\n"
"            + '<div style=\"font-size:14px;color:var(--s300);\">Complete your profile to start receiving leads. Profile ' + pct + '% complete.</div>'\r\n"
"            + '</div>'\r\n"
"            + '<a onclick=\"switchTab(\\'tab-profile\\',document.querySelectorAll(\\'.tab-btn\\')[4])\" class=\"btn btn-orange btn-sm\" style=\"cursor:pointer;\">Complete Profile &#8594;</a>'\r\n"
"            + '</div>'\r\n"
"            + '<div style=\"background:var(--n600);border-radius:999px;height:6px;margin-bottom:20px;overflow:hidden;\">'\r\n"
"            + '<div style=\"background:linear-gradient(90deg,var(--o500),#F0C040);height:100%;width:' + pct + '%;border-radius:999px;transition:width 0.4s;\"></div>'\r\n"
"            + '</div>'\r\n"
"            + '<div style=\"display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px;\">'\r\n"
"            + steps.map(function(s) {\r\n"
"                return '<div style=\"display:flex;align-items:center;gap:10px;font-size:13px;color:' + (s.done ? '#6FE09A' : 'var(--s300)') + ';background:' + (s.done ? 'rgba(34,197,94,0.08)' : 'var(--n700)') + ';border:1px solid ' + (s.done ? 'rgba(34,197,94,0.25)' : 'var(--n500)') + ';border-radius:6px;padding:8px 12px;\">'\r\n"
"                  + '<span style=\"font-size:16px;\">' + (s.done ? '&#10003;' : '&#9711;') + '</span> ' + s.label\r\n"
"                  + '</div>';\r\n"
"              }).join('')\r\n"
"            + '</div></div>';\r\n"
"        }\r\n"
"        return '';\r\n"
"      })()}\r\n"
"\r\n"
"      ${(function(){\r\n"
"        /* ── Upgrade banner — free plan only ── */\r\n"
"        if (prov.plan && prov.plan !== 'free') return '';\r\n"
"        const matchingLeads = (App.rfqs || []).filter(function(r){ return r.status==='open' && r.tradeType===prov.tradeType; });\r\n"
"        const hiddenCount = Math.max(0, matchingLeads.length - 5);\r\n"
"        if (hiddenCount === 0) return '';\r\n"
"        return '<div style=\"background:linear-gradient(135deg,#1A0E00,#2C1A00);border:1px solid var(--o600);border-radius:10px;padding:16px 24px;margin-bottom:28px;display:flex;align-items:center;gap:16px;flex-wrap:wrap;\">'\r\n"
"          + '<span style=\"font-size:22px;\">&#128274;</span>'\r\n"
"          + '<span style=\"flex:1;font-size:14px;color:var(--s200);\"><strong style=\"color:var(--o300);\">' + hiddenCount + ' leads locked</strong> on your Free plan. Upgrade to Pro to see all ' + matchingLeads.length + ' matching ' + prov.tradeType + ' leads in your area.</span>'\r\n"
"          + '<button onclick=\"navigate(\\'/pricing\\')\" class=\"btn btn-orange btn-sm\" style=\"white-space:nowrap;\">Unlock All Leads &#8594;</button>'\r\n"
"          + '</div>';\r\n"
"      })()}\r\n"
"\r\n"
"      <div class=\"dash-stats\" style=\"display:grid;grid-template-columns:repeat(5,1fr);gap:16px;margin-bottom:40px;\">\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\">${(App.rfqs||[]).filter(r=>r.status==='open'&&r.tradeType===prov.tradeType).length}</div><div class=\"stat-label\">Open Leads</div></div>\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\">${bookings.length}</div><div class=\"stat-label\">Appointments</div></div>\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\" style=\"color:#F0A030;\">${pending.length}</div><div class=\"stat-label\">Awaiting Review</div></div>\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\" style=\"color:#22C55E;\">${confirmed.length}</div><div class=\"stat-label\">Confirmed</div></div>\r\n"
"        <div class=\"stat-card\"><div class=\"stat-value\">${profileViews}</div><div class=\"stat-label\">Profile Views</div></div>\r\n"
"      </div>\r\n"
"\r\n"
"      <div class=\"tab-bar\">\r\n"
"        <button class=\"tab-btn active\" onclick=\"switchTab('tab-leads',this)\">&#128203; Leads ${(function(){var n=(App.rfqs||[]).filter(r=>r.status==='open'&&r.tradeType===prov.tradeType).length;return n>0?'<span style=\"background:var(--o500);color:white;border-radius:999px;padding:1px 7px;font-size:11px;margin-left:4px;\">' +n+ '</span>':'';}())}</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-appt',this)\">&#128197; Appointments ${pending.length>0?'<span style=\"background:#F0A030;color:white;border-radius:999px;padding:1px 7px;font-size:11px;margin-left:4px;\">'+pending.length+'</span>':''}</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-analytics',this)\">&#128200; Analytics</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-notifs',this)\">\r\n"
"          &#128276; Notifications${unread>0?` <span style=\"background:var(--o500);color:white;border-radius:50%;width:18px;height:18px;display:inline-flex;align-items:center;justify-content:center;font-size:10px;margin-left:4px;\">${unread}</span>`:''}\r\n"
"        </button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-reviews',this)\">&#9733; Reviews</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-profile',this)\">&#9881;&#65039; Profile</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-reputation',this)\">&#127942; Reputation &amp; XP</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-avail',this)\">&#128336; Availability</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-post-job',this)\">&#128226; Post a Job</button>\r\n"
"        <button class=\"tab-btn\" onclick=\"switchTab('tab-photos',this)\">&#128247; Photos</button>\r\n"
"      </div>"
)

print("stats+tabs found:", OLD_STATS_TABS in content)
content = content.replace(OLD_STATS_TABS, NEW_STATS_TABS, 1)

# ── 2. Add the Leads tab content block right before the Appointments tab block ─
OLD_APPT_COMMENT = "      <!-- Appointments -->\r\n      <div id=\"tab-appt\" class=\"tab-content active\">"
NEW_LEADS_PLUS_APPT = (
"      <!-- Leads Tab -->\r\n"
"      <div id=\"tab-leads\" class=\"tab-content active\">\r\n"
"        ${(function(){\r\n"
"          const isPro = prov.plan==='pro' || prov.plan==='enterprise';\r\n"
"          const allLeads = (App.rfqs||[]).filter(function(r){ return r.status==='open' && r.tradeType===prov.tradeType; })\r\n"
"            .sort(function(a,b){ return new Date(b.createdAt)-new Date(a.createdAt); });\r\n"
"          const FREE_LIMIT = 5;\r\n"
"          const freeLeads   = allLeads.slice(0, FREE_LIMIT);\r\n"
"          const lockedLeads = allLeads.slice(FREE_LIMIT);\r\n"
"\r\n"
"          if (allLeads.length === 0) {\r\n"
"            return '<div style=\"text-align:center;padding:70px 40px;\">'\r\n"
"              + '<div style=\"font-size:48px;margin-bottom:16px;\">&#128203;</div>'\r\n"
"              + '<div style=\"font-family:\\'Barlow Condensed\\',sans-serif;font-size:26px;color:white;margin-bottom:8px;\">No leads yet for ' + prov.tradeType + '</div>'\r\n"
"              + '<div style=\"font-size:14px;color:var(--s400);max-width:400px;margin:0 auto 24px;\">When clients post job requests matching your trade and city, they appear here automatically. Check back soon!</div>'\r\n"
"              + '<button onclick=\"navigate(\\'/rfq\\')\" class=\"btn btn-orange\">&#128226; Post Your Own Job Request</button>'\r\n"
"              + '</div>';\r\n"
"          }\r\n"
"\r\n"
"          function renderLead(job, isLocked) {\r\n"
"            const urgencyBadge = job.urgency==='high' ? '<span style=\"background:rgba(239,68,68,0.15);border:1px solid rgba(239,68,68,0.4);color:#FCA5A5;font-size:11px;font-family:\\'Barlow Condensed\\',sans-serif;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;padding:3px 8px;border-radius:4px;\">&#128308; Urgent</span>' : '';\r\n"
"            if (isLocked) {\r\n"
"              return '<div style=\"position:relative;border-radius:10px;overflow:hidden;margin-bottom:12px;\">'\r\n"
"                + '<div style=\"filter:blur(5px);pointer-events:none;user-select:none;background:var(--n700);border:1px solid var(--n500);border-radius:10px;padding:22px 26px;\">'\r\n"
"                + '<div style=\"font-family:\\'Barlow Condensed\\',sans-serif;font-weight:700;font-size:19px;color:white;margin-bottom:8px;\">' + (job.title||'Lead Request') + '</div>'\r\n"
"                + '<div style=\"display:flex;gap:14px;font-size:13px;color:var(--s400);\"><span>&#128205; ' + (job.city||'') + ', ' + (job.province||'') + '</span><span>&#128178; ' + (job.budget||'') + '</span><span>&#128336; ' + (job.timeline||'') + '</span></div>'\r\n"
"                + '<div style=\"font-size:14px;color:var(--s300);margin-top:8px;line-height:1.5;\">' + (job.jobDescription||'').slice(0,100) + '...</div>'\r\n"
"                + '</div>'\r\n"
"                + '<div style=\"position:absolute;inset:0;background:rgba(11,17,26,0.75);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;\">'\r\n"
"                + '<span style=\"font-size:28px;\">&#128274;</span>'\r\n"
"                + '<div style=\"font-family:\\'Barlow Condensed\\',sans-serif;font-size:16px;color:white;font-weight:700;\">Unlock with Pro Membership</div>'\r\n"
"                + '<button onclick=\"navigate(\\'/pricing\\')\" class=\"btn btn-orange btn-sm\">Upgrade to Pro &#8594;</button>'\r\n"
"                + '</div>'\r\n"
"                + '</div>';\r\n"
"            }\r\n"
"            return '<div style=\"background:var(--n700);border:1px solid var(--n500);border-radius:10px;padding:22px 26px;margin-bottom:12px;display:flex;align-items:flex-start;gap:20px;flex-wrap:wrap;\">'\r\n"
"              + '<div style=\"flex:1;min-width:240px;\">'\r\n"
"              + '<div style=\"display:flex;align-items:center;gap:10px;margin-bottom:8px;flex-wrap:wrap;\">'\r\n"
"              + '<div style=\"font-family:\\'Barlow Condensed\\',sans-serif;font-weight:700;font-size:19px;color:white;\">' + (job.title||'Lead Request') + '</div>'\r\n"
"              + urgencyBadge\r\n"
"              + '</div>'\r\n"
"              + '<div style=\"display:flex;gap:14px;flex-wrap:wrap;font-size:13px;color:var(--s400);margin-bottom:10px;\">'\r\n"
"              + '<span>&#128205; ' + (job.city||'') + ', ' + (job.province||'') + '</span>'\r\n"
"              + '<span>&#128178; ' + (job.budget||'TBD') + '</span>'\r\n"
"              + '<span>&#128336; ' + (job.timeline||'Flexible') + '</span>'\r\n"
"              + '<span>&#128197; ' + (job.createdAt ? new Date(job.createdAt).toLocaleDateString('en-CA') : '') + '</span>'\r\n"
"              + '</div>'\r\n"
"              + (job.jobDescription ? '<div style=\"font-size:14px;color:var(--s300);line-height:1.6;margin-bottom:12px;\">' + job.jobDescription + '</div>' : '')\r\n"
"              + '<div style=\"font-size:13px;color:var(--s400);\">&#128100; <strong style=\"color:var(--s200);\">' + (job.contactName||'Client') + '</strong></div>'\r\n"
"              + '</div>'\r\n"
"              + '<div style=\"flex-shrink:0;display:flex;flex-direction:column;gap:8px;min-width:160px;\">'\r\n"
"              + '<a href=\"mailto:' + (job.contactEmail||'') + '\" class=\"btn btn-orange btn-sm\" style=\"text-align:center;\">&#128140; Email Client</a>'\r\n"
"              + (job.contactPhone ? '<a href=\"tel:' + job.contactPhone + '\" class=\"btn btn-outline btn-sm\" style=\"text-align:center;font-size:12px;\">&#128222; ' + job.contactPhone + '</a>' : '')\r\n"
"              + '</div>'\r\n"
"              + '</div>';\r\n"
"          }\r\n"
"\r\n"
"          var html = '';\r\n"
"\r\n"
"          if (!isPro && lockedLeads.length > 0) {\r\n"
"            html += '<div style=\"background:linear-gradient(135deg,#0D1F0D,#1A3A1A);border:1px solid rgba(34,197,94,0.25);border-radius:10px;padding:18px 24px;margin-bottom:24px;display:flex;align-items:center;gap:14px;flex-wrap:wrap;\">'\r\n"
"              + '<span style=\"font-size:20px;\">&#127381;</span>'\r\n"
"              + '<span style=\"flex:1;font-size:14px;color:var(--s200);\"><strong style=\"color:#6FE09A;\">' + allLeads.length + ' ' + prov.tradeType + ' leads</strong> in your area. First 5 are free. <strong style=\"color:white;\">' + lockedLeads.length + ' more</strong> locked behind Pro.</span>'\r\n"
"              + '<button onclick=\"navigate(\\'/pricing\\')\" class=\"btn btn-orange btn-sm\">Unlock All &#8594;</button>'\r\n"
"              + '</div>';\r\n"
"          } else if (isPro) {\r\n"
"            html += '<div style=\"background:rgba(34,197,94,0.06);border:1px solid rgba(34,197,94,0.2);border-radius:8px;padding:14px 20px;margin-bottom:20px;display:flex;align-items:center;gap:12px;\">'\r\n"
"              + '<span style=\"font-size:16px;\">&#9989;</span>'\r\n"
"              + '<span style=\"font-size:14px;color:var(--s300);\">Full lead access active &mdash; <strong style=\"color:var(--o400);\">' + allLeads.length + ' open ' + prov.tradeType + ' leads</strong> in your area.</span>'\r\n"
"              + '</div>';\r\n"
"          }\r\n"
"\r\n"
"          const visibleLeads = isPro ? allLeads : freeLeads;\r\n"
"          html += visibleLeads.map(function(j){ return renderLead(j, false); }).join('');\r\n"
"          if (!isPro && lockedLeads.length > 0) {\r\n"
"            html += lockedLeads.map(function(j){ return renderLead(j, true); }).join('');\r\n"
"            html += '<div style=\"background:linear-gradient(135deg,#1A0E00,#2C1A00);border:2px solid var(--o500);border-radius:12px;padding:28px 32px;margin-top:24px;text-align:center;\">'\r\n"
"              + '<div style=\"font-size:36px;margin-bottom:12px;\">&#128081;</div>'\r\n"
"              + '<div style=\"font-family:\\'Barlow Condensed\\',sans-serif;font-weight:700;font-size:24px;color:white;margin-bottom:8px;\">Unlock All ' + allLeads.length + ' Leads with Pro</div>'\r\n"
"              + '<p style=\"font-size:14px;color:var(--s300);max-width:480px;margin:0 auto 20px;line-height:1.6;\">Get full contact details, project budgets, and timelines for every matching ' + prov.tradeType + ' lead posted in Canada.</p>'\r\n"
"              + '<div style=\"display:flex;justify-content:center;gap:24px;flex-wrap:wrap;margin-bottom:20px;\">'\r\n"
"              + '<div style=\"display:flex;align-items:center;gap:8px;font-size:13px;color:var(--s200);\"><span style=\"color:#22C55E;font-weight:700;\">&#10003;</span> Unlimited lead access</div>'\r\n"
"              + '<div style=\"display:flex;align-items:center;gap:8px;font-size:13px;color:var(--s200);\"><span style=\"color:#22C55E;font-weight:700;\">&#10003;</span> Full client contact info</div>'\r\n"
"              + '<div style=\"display:flex;align-items:center;gap:8px;font-size:13px;color:var(--s200);\"><span style=\"color:#22C55E;font-weight:700;\">&#10003;</span> Priority listing placement</div>'\r\n"
"              + '</div>'\r\n"
"              + '<button onclick=\"navigate(\\'/pricing\\')\" class=\"btn btn-orange\" style=\"font-size:16px;padding:14px 36px;\">Upgrade to Pro &mdash; from $49/mo &#8594;</button>'\r\n"
"              + '</div>';\r\n"
"          }\r\n"
"          return html;\r\n"
"        })()}\r\n"
"      </div>\r\n"
"\r\n"
"      <!-- Appointments -->\r\n"
"      <div id=\"tab-appt\" class=\"tab-content\">"
)

print("appt comment found:", OLD_APPT_COMMENT in content)
content = content.replace(OLD_APPT_COMMENT, NEW_LEADS_PLUS_APPT, 1)

open('C:/Personal/trades-ontario/index.html', 'w', encoding='utf-8', newline='').write(content)
print("Done - dashboard rebuilt, length:", len(content))
